# apps/grades/urls.py
from django.urls import path
from . import views

app_name = 'grades'

urlpatterns = [
    path('grade-entry/', views.grade_entry, name='grade_entry'),
    path('api/filters/', views.get_filters_api, name='get_filters'),
    path('api/get-courses-by-level/', views.get_courses_by_level_api, name='get_courses_by_level'),
    path('api/get-groups-by-filter/', views.get_groups_by_filter_api, name='get_groups_by_filter'),
    path('api/students/', views.get_students_for_grades_api, name='get_students'),
    path('api/save-grades/', views.save_grades_api, name='save_grades'),
    path('api/grades/import-excel/', views.import_excel_grades_api, name='import_excel_grades'),
    path('api/approve-and-lock/', views.approve_and_lock_grades_api, name='approve_and_lock'),
    path('api/export-excel/', views.export_excel_grades_api, name='export_excel'),
    path('api/publish-grades/', views.publish_grades_api, name='publish_grades'),
    path('api/check-lock-status/', views.check_lock_status_api, name='check_lock_status'),
    path('api/get-results/', views.get_results_api, name='get_results_api'),
    path('api/student-transcript/', views.get_student_transcript_api, name='student_transcript'),
    path('cumulative-grades/', views.cumulative_grades, name='cumulative_grades'),
    path('show-results/', views.show_results, name='show_results'),
    path('course-equivalence/', views.course_equivalence_page, name='course_equivalence'),
    path('api/toggle-equivalence-job/', views.toggle_equivalence_job_api, name='toggle_equivalence_job_api'),
    path('equivalence-rules/', views.course_equivalence_rules, name='course_equivalence_rules'),
    path('equivalence-rules/delete/<int:rule_id>/', views.delete_course_equivalence_rule, name='delete_course_equivalence_rule'),
    path('equivalent-students/', views.equivalent_students, name='equivalent_students'),
    path('successful-students/', views.successful_students_report, name='successful_students'),
    path('academic-status/', views.academic_status, name='academic_status'),
    path('failed-students-report/', views.failed_students_report, name='failed_students_report'),
    path('show-results/', views.show_results, name='show_results'),
    path('api/get-results-filters/', views.get_results_filters_api, name='get_results_filters_api'),
    path('api/search-students/', views.search_students_api, name='search_students_api'),
    path('api/get-student-results/', views.get_student_results_api, name='get_student_results_api'),
    path('control-holds/', views.control_holds_page, name='control_holds'),
    path('api/control-holds/students/', views.get_control_holds_students_api, name='get_control_holds_students'),
    path('api/toggle-block/', views.toggle_block_grade_api, name='toggle_block_grade'),
    path('publish-results/', views.publish_results_page, name='publish_results'),
    path('api/get-courses-publish-status/', views.get_courses_publish_status_api, name='get_courses_publish_status'),
    path('appeals/', views.grade_appeals_page, name='grade_appeals'),
    path('pending-approvals/', views.pending_approvals_page, name='pending_approvals'),
    path('api/appeals/', views.get_appeals_api, name='get_appeals_api'),
    path('api/appeals/create/', views.create_appeal_api, name='create_appeal_api'),
    path('api/appeals/update-status/', views.update_appeal_status_api, name='update_appeal_status_api'),
    path('api/appeals/update-grade/', views.update_appeal_grade_api, name='update_appeal_grade_api'),
    path('api/professor-grade-reply/', views.professor_grade_email_reply_api, name='professor_grade_email_reply_api'),
    path('api/check-email-replies/', views.check_inbox_grade_replies_api, name='check_inbox_grade_replies_api'),
    path('api/simulate-grade-reply/', views.simulate_professor_grade_reply_api, name='simulate_professor_grade_reply_api'),
    path('coordinator-dashboard/', views.coordinator_dashboard_view, name='coordinator_dashboard'),
]  