# Generated by Django 5.2.7 on 2026-07-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0007_enrollmentrenewal_special_type_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewal.department', verbose_name='القسم العلمي التابع له'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('registrar', 'موظف تسجيل وقبول'), ('exam_officer', 'موظف دراسة وامتحانات'), ('graduate_officer', 'قسم الخريجين'), ('academic_dept', 'رئيس / قسم علمي'), ('student', 'طالب')], default='student', max_length=20, verbose_name='الدور'),
        ),
    ]
