# Generated by Django 6.0.7 on 2026-08-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.CharField(choices=[('dean', 'العميد / عميد الكلية'), ('registrar', 'المسجل العام'), ('admission', 'قسم التسجيل والقبول'), ('exams', 'قسم الدراسة والامتحانات'), ('graduates', 'قسم الخريجين'), ('vice_dean', 'وكيل الشؤون العلمية'), ('admin_affairs', 'مدير الشؤون الإدارية'), ('other', 'منصب آخر')], default='other', max_length=50, verbose_name='رمز/مفتاح المنصب')),
                ('position_name', models.CharField(max_length=150, verbose_name='اسم المنصب/الوظيفة')),
                ('official_name', models.CharField(max_length=150, verbose_name='اسم المسؤول')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='الصفة/اللقب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط/حالي')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية التكليف')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مسؤول معتمد',
                'verbose_name_plural': 'المسؤولين المعتمدين',
                'ordering': ['-is_active', 'position_name'],
            },
        ),
    ]
