# Generated by Django 5.2.7 on 2026-08-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('general_registrar', 'مسجل عام'), ('registrar', 'موظف تسجيل وقبول'), ('exam_officer', 'موظف دراسة وامتحانات'), ('graduate_officer', 'قسم الخريجين'), ('academic_dept', 'رئيس / قسم علمي'), ('student', 'طالب')], default='student', max_length=20, verbose_name='الدور'),
        ),
    ]
