# Generated by Django 5.2.7 on 2026-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='position_key',
            field=models.CharField(choices=[('dean', 'العميد / عميد الكلية'), ('registrar', 'المسجل العام'), ('admission', 'قسم التسجيل والقبول'), ('exams_coordinator', 'منسق/ة الدراسة والامتحانات'), ('exams_head', 'رئيس قسم الدراسة والامتحانات'), ('exams', 'قسم الدراسة والامتحانات'), ('graduates', 'قسم الخريجين'), ('vice_dean', 'وكيل الشؤون العلمية'), ('admin_affairs', 'مدير الشؤون الإدارية'), ('department_head', 'رئيس قسم علمي'), ('department_coordinator', 'منسق قسم علمي'), ('other', 'منصب آخر')], default='other', max_length=50, verbose_name='رمز/مفتاح المنصب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('general_registrar', 'مسجل عام'), ('registrar', 'موظف تسجيل وقبول'), ('exam_director', 'مدير الدراسة والامتحانات'), ('exam_officer', 'موظف دراسة وامتحانات'), ('graduate_officer', 'قسم الخريجين'), ('academic_dept', 'رئيس / قسم علمي'), ('student', 'طالب')], default='student', max_length=20, verbose_name='الدور'),
        ),
    ]
