# Generated by Django 5.2.7 on 2026-09-03 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_official_position_key_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='مطلوب. 150 حرفاً أو أقل. الأحرف والأرقام والمسافات والرموز @/./+/-/_ فقط.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل اسم مستخدم صالحاً. قد يحتوي هذا الحقل على أحرف، أرقام، مسافات، ورموز @/./+/-/_ فقط.', regex='^[\\w.@+\\-\\s]+$')], verbose_name='اسم المستخدم'),
        ),
    ]
