# Generated by Django 6.0.7 on 2026-07-19 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('dropped_out', 'منقطع'), ('withdrawn', 'سحب ملف'), ('cleared', 'إخلاء طرف'), ('graduated', 'متخرج')], default='active', max_length=20, verbose_name='حالة القيد')),
                ('renewal_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التجديد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تجديد قيد',
                'verbose_name_plural': 'تجديدات القيد',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المجموعة')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوظيفة')),
                ('description', models.TextField(verbose_name='وصف الوظيفة')),
                ('requirements', models.TextField(verbose_name='المتطلبات')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالة')),
            ],
            options={
                'verbose_name': 'وظيفة',
                'verbose_name_plural': 'الوظائف',
                'ordering': ['-posted_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='رقم المستوى')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المستوى')),
            ],
            options={
                'verbose_name': 'مستوى دراسي',
                'verbose_name_plural': 'المستويات الدراسية',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('type', models.CharField(choices=[('fall', 'خريف'), ('spring', 'ربيع')], max_length=10, verbose_name='نوع الفصل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الخطة')),
            ],
            options={
                'verbose_name': 'خطة دراسية',
                'verbose_name_plural': 'الخطط الدراسية',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المادة')),
                ('credits', models.IntegerField(default=3, verbose_name='عدد الوحدات')),
                ('theoretical_hours', models.IntegerField(default=2, verbose_name='ساعات نظري')),
                ('practical_hours', models.IntegerField(default=0, verbose_name='ساعات عملي')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعالة')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إجبارية')),
                ('prerequisites', models.ManyToManyField(blank=True, to='renewal.course', verbose_name='المتطلبات السابقة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'ordering': ['level__number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='عدد المحاولة')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التنزيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.course', verbose_name='المادة')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم التنزيل بواسطة')),
            ],
            options={
                'verbose_name': 'تنزيل مادة',
                'verbose_name_plural': 'تنزيل المواد',
            },
        ),
    ]
