# Generated by Django 6.0.7 on 2026-07-19 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renewal', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='enrollmentrenewal',
            name='renewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم التجديد بواسطة'),
        ),
        migrations.AddField(
            model_name='enrollmentrenewal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renewal.level', verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='enrollmentrenewal',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.level', verbose_name='المستوى'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.level', verbose_name='المستوى'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'type')},
        ),
        migrations.AddField(
            model_name='enrollmentrenewal',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.studyplan', verbose_name='الخطة الدراسية'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'department', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentrenewal',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
