# Generated by Django 6.0.7 on 2026-07-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التخصص')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز التخصص')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
            },
        ),
    ]
