# Generated by Django 6.0.7 on 2026-07-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0003_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
