# Generated by Django 6.0.7 on 2026-07-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0004_department_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوظيفة')),
                ('code', models.SlugField(help_text='رمز فريد للوظيفة لربطها في الكود (مثل: renewal, registration)', unique=True, verbose_name='الرمز البرمجي')),
                ('start_date', models.DateField(verbose_name='تاريخ الفتح')),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='عدد الأيام المتاحة لإنجاز الوظيفة', verbose_name='المدة بالأيام')),
                ('is_active', models.BooleanField(default=True, help_text='تفعيل أو إيقاف الوظيفة يدوياً', verbose_name='مفعلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وظيفة/خدمة',
                'verbose_name_plural': 'الوظائف والخدمات',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
