# Generated by Django 5.2.7 on 2026-07-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0005_systemjob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='group',
            name='academic_year',
            field=models.CharField(default='2026', max_length=20, verbose_name='السنة الدراسية'),
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.CharField(default='spring', max_length=20, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'department', 'level', 'academic_year', 'semester')},
        ),
    ]
