# Generated by Django 5.2.7 on 2026-07-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0006_alter_group_unique_together_group_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrenewal',
            name='special_type',
            field=models.CharField(choices=[('REGULAR', 'عادي'), ('STOPPED', 'موقوف قيده'), ('STOPPED_ENROLLMENT', 'موقوف قيده'), ('NEW_STUDENT', 'طالب جديد'), ('OTHER', 'حالة خاصة أخرى')], default='REGULAR', max_length=50, verbose_name='نوع التجديد الخاص'),
        ),
        migrations.AlterField(
            model_name='enrollmentrenewal',
            name='status',
            field=models.CharField(choices=[('RENEWED', 'مجدد'), ('active', 'نشط'), ('suspended', 'موقوف'), ('dropped_out', 'منقطع'), ('withdrawn', 'سحب ملف'), ('cleared', 'إخلاء طرف'), ('graduated', 'متخرج')], default='RENEWED', max_length=20, verbose_name='حالة القيد'),
        ),
    ]
