# Generated by Django 6.0.7 on 2026-07-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0007_enrollmentrenewal_special_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEquivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات المعادلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('source_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_equivalences', to='renewal.course', verbose_name='المادة الأصلية / المصدر')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_equivalences', to='renewal.course', verbose_name='المادة البديلة / المكافئة')),
            ],
            options={
                'verbose_name': 'قاعدة معادلة مادة',
                'verbose_name_plural': 'قواعد معادلة المواد',
                'ordering': ['-created_at'],
                'unique_together': {('source_course', 'target_course')},
            },
        ),
    ]
