# Generated by Django 6.0.7 on 2026-07-30 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0008_courseequivalence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisite_for', to='renewal.course', verbose_name='المتطلبات السابقة'),
        ),
        migrations.AlterField(
            model_name='enrollmentrenewal',
            name='renewal_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التجديد'),
        ),
    ]
