# Generated by Django 6.0.7 on 2026-08-05 23:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0009_alter_course_prerequisites_and_more'),
        ('student', '0006_student_passport_number_alter_student_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, verbose_name='رمز المادة'),
        ),
        migrations.CreateModel(
            name='GraduationClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clearance_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ إخلاء الطرف')),
                ('graduation_project_grade', models.FloatField(default=0.0, verbose_name='درجة مشروع التخرج')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات وتفاصيل إخلاء الطرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم التوثيق بواسطة')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='فصل التخرج')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_clearance', to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'إخلاء طرف خريج',
                'verbose_name_plural': 'إخلاءات طرف الخريجين',
            },
        ),
    ]
