# Generated by Django 6.0.7 on 2026-08-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0009_alter_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, verbose_name='رمز المادة'),
        ),
    ]
