# Generated by Django 6.0.7 on 2026-08-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0010_alter_course_code'),
        ('renewal', '0010_alter_course_code_graduationclearance'),
    ]

    operations = [
    ]
