# Generated by Django 6.0.7 on 2026-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0011_merge_20260806'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationclearance',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إصدار الإفادة'),
        ),
        migrations.AddField(
            model_name='graduationclearance',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم إفادة التخرج'),
        ),
        migrations.AddField(
            model_name='graduationclearance',
            name='is_certificate_issued',
            field=models.BooleanField(default=False, verbose_name='تم إصدار الإفادة'),
        ),
    ]
