# Generated by Django 6.0.7 on 2026-08-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0012_graduationclearance_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='studyplan',
                    name='code',
                    field=models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name='رمز الخطة',
                    ),
                ),
            ],
        ),
    ]
