# Generated by Django 5.2.7 on 2026-08-15 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0013_studyplan_code'),
        ('student', '0008_student_qr_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrenewal',
            name='status',
            field=models.CharField(choices=[('RENEWED', 'مجدد'), ('active', 'منتظم'), ('suspended', 'موقوف'), ('dropped_out', 'منقطع'), ('withdrawn', 'سحب ملف'), ('cleared', 'إخلاء طرف'), ('graduated', 'متخرج')], default='RENEWED', max_length=20, verbose_name='حالة القيد'),
        ),
        migrations.CreateModel(
            name='StudentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ السحب')),
                ('reason', models.TextField(verbose_name='سبب سحب الملف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوثيق')),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل سحب ملف',
                'verbose_name_plural': 'أرشيف سحب الملفات',
                'ordering': ['-withdrawal_date', '-created_at'],
            },
        ),
    ]
