# Generated by Django 5.2.7 on 2026-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0014_alter_enrollmentrenewal_status_studentwithdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='courses', to='renewal.department', verbose_name='الأقسام والتخصصات'),
        ),
    ]
