# Generated by Django 5.2.7 on 2026-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0015_remove_course_department_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
    ]
