# Generated by Django 5.2.7 on 2026-08-31 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0016_studyplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_plan_code', message='رمز الخطة يجب أن يتراوح طوله بين 2 إلى 20 خانة، ويحتوي على حرف ورقم على الأقل.', regex='^(?=.*[a-zA-Z\\u0600-\\u06FF])(?=.*\\d)[a-zA-Z0-9\\u0600-\\u06FF\\-_./]{2,20}$')], verbose_name='رمز الخطة'),
        ),
    ]
