# Generated by Django 5.2.7 on 2026-09-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0017_alter_studyplan_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_equivalences', to='renewal.department', verbose_name='القسم / التخصص العلمي'),
        ),
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together={('department', 'source_course', 'target_course')},
        ),
    ]
