# Generated by Django 5.2.7 on 2026-09-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0018_alter_courseequivalence_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='source_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_course_equivalences', to='renewal.department', verbose_name='تخصص المادة الأصلية (المحول منه)'),
        ),
        migrations.AddField(
            model_name='courseequivalence',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_course_equivalences', to='renewal.department', verbose_name='تخصص المادة البديلة (المحول إليه)'),
        ),
        migrations.RemoveField(
            model_name='courseequivalence',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='courseequivalence',
            unique_together={('source_department', 'source_course', 'target_department', 'target_course')},
        ),
    ]
