# Generated by Django 6.0.7 on 2026-07-20 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('renewal', '0003_specialization'),
        ('student', '0002_academicrecord_semesterrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_final_to_combine', models.FloatField(default=30, verbose_name='الحد الأدنى للنهائي (من 60)')),
                ('passing_score', models.FloatField(default=50, verbose_name='درجة النجاح (من 100)')),
                ('final_weight', models.FloatField(default=60, verbose_name='وزن الامتحان النهائي')),
                ('midterm_weight', models.FloatField(default=40, verbose_name='وزن الامتحان النصفي')),
                ('practical_weight', models.FloatField(default=0, verbose_name='وزن الأعمال العملية')),
                ('is_active', models.BooleanField(default=True, verbose_name='الإعدادات فعالة')),
            ],
            options={
                'verbose_name': 'إعدادات الدرجات',
                'verbose_name_plural': 'إعدادات الدرجات',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='عدد المحاولات')),
                ('final_grade', models.FloatField(default=0, verbose_name='درجة الامتحان النهائي (60)')),
                ('midterm_grade', models.FloatField(default=0, verbose_name='درجة الامتحان النصفي (40)')),
                ('practical_grade', models.FloatField(default=0, verbose_name='درجة الأعمال العملية')),
                ('total_grade', models.FloatField(default=0, verbose_name='الدرجة النهائية المحسوبة')),
                ('is_passed', models.BooleanField(default=False, verbose_name='ناجح/راسب')),
                ('is_final_entered', models.BooleanField(default=False, verbose_name='تم إدخال النهائي')),
                ('is_midterm_locked', models.BooleanField(default=False, verbose_name='درجة النصفي مقفلة')),
                ('is_final_locked', models.BooleanField(default=False, verbose_name='درجة النهائي مقفلة')),
                ('registered_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.course', verbose_name='المادة')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='faculty.professor', verbose_name='الأستاذ')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم التسجيل بواسطة')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='renewal.group', verbose_name='المجموعة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تحديث بواسطة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
                'ordering': ['-semester__year', '-semester__type', 'course__code'],
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_final_grade', models.FloatField(verbose_name='النهائي القديم')),
                ('old_midterm_grade', models.FloatField(verbose_name='النصفي القديم')),
                ('old_practical_grade', models.FloatField(verbose_name='الأعمال القديم')),
                ('new_final_grade', models.FloatField(verbose_name='النهائي الجديد')),
                ('new_midterm_grade', models.FloatField(verbose_name='النصفي الجديد')),
                ('new_practical_grade', models.FloatField(verbose_name='الأعمال الجديد')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعديل')),
                ('reason', models.TextField(blank=True, verbose_name='سبب التعديل')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم التعديل بواسطة')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade', verbose_name='الدرجة')),
            ],
            options={
                'verbose_name': 'تاريخ تعديل درجة',
                'verbose_name_plural': 'تاريخ تعديل الدرجات',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('period', models.CharField(max_length=50, verbose_name='فترة الرصد')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.course', verbose_name='المادة')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faculty.professor', verbose_name='الأستاذ')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='الفصل الدراسي')),
            ],
            options={
                'verbose_name': 'إشعار درجات',
                'verbose_name_plural': 'إشعارات الدرجات',
                'ordering': ['-created_at'],
            },
        ),
    ]
