# Generated by Django 5.2.7 on 2026-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='block_reason',
            field=models.CharField(blank=True, default='تجاوز نسبة الغياب الورقي', max_length=255, null=True, verbose_name='سبب الحجب'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='حجب النتيجة'),
        ),
    ]
