# Generated by Django 5.2.7 on 2026-07-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_grade_block_reason_grade_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_final_published',
            field=models.BooleanField(default=False, verbose_name='تم نشر نتيجة النهائي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_midterm_published',
            field=models.BooleanField(default=False, verbose_name='تم نشر نتيجة النصفي'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منشورة للطالب'),
        ),
    ]
