# Generated by Django 5.2.7 on 2026-07-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_is_final_published_grade_is_midterm_published_and_more'),
        ('renewal', '0007_enrollmentrenewal_special_type_and_more'),
        ('student', '0004_merge_20260725_0437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('midterm', 'امتحان نصفي'), ('final', 'امتحان نهائي'), ('total', 'إجمالي الدرجة')], default='midterm', max_length=20, verbose_name='نوع الطعن')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('under_review', 'جاري المراجعة والتعديل'), ('completed', 'تم تعديل ورصد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطعن')),
                ('old_midterm_grade', models.FloatField(blank=True, null=True, verbose_name='درجة النصفي السابقة')),
                ('new_midterm_grade', models.FloatField(blank=True, null=True, verbose_name='درجة النصفي الجديدة')),
                ('old_final_grade', models.FloatField(blank=True, null=True, verbose_name='درجة النهائي السابقة')),
                ('new_final_grade', models.FloatField(blank=True, null=True, verbose_name='درجة النهائي الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='سبب / ملاحظات الطعن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ تقديم الطعن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.course', verbose_name='المادة')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grades.grade', verbose_name='سجل الدرجة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طعن نتيجة',
                'verbose_name_plural': 'طعونات النتائج',
                'ordering': ['-created_at'],
            },
        ),
    ]
