# Generated by Django 6.0.7 on 2026-07-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renewal', '0003_specialization'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered_credits', models.FloatField(default=0, verbose_name='إجمالي الساعات المسجلة')),
                ('total_completed_credits', models.FloatField(default=0, verbose_name='إجمالي الساعات المنجزة')),
                ('total_points', models.FloatField(default=0, verbose_name='مجموع النقاط التراكمية')),
                ('cumulative_gpa', models.FloatField(default=0, verbose_name='المعدل التراكمي cGPA')),
                ('passed_courses_count', models.IntegerField(default=0, verbose_name='إجمالي المواد الناجحة')),
                ('failed_courses_count', models.IntegerField(default=0, verbose_name='إجمالي المواد الراسبة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل أكاديمي',
                'verbose_name_plural': 'السجلات الأكاديمية',
            },
        ),
        migrations.CreateModel(
            name='SemesterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='رقم القيد')),
                ('registered_credits', models.FloatField(default=0, verbose_name='الساعات المسجلة في الفصل')),
                ('completed_credits', models.FloatField(default=0, verbose_name='الساعات المنجزة الناجحة في الفصل')),
                ('semester_points', models.FloatField(default=0, verbose_name='مجموع النقاط الفصلية')),
                ('semester_gpa', models.FloatField(default=0, verbose_name='المعدل الفصلي GPA')),
                ('passed_courses', models.IntegerField(default=0, verbose_name='عدد المواد الناجحة')),
                ('failed_courses', models.IntegerField(default=0, verbose_name='عدد المواد الراسبة')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل فصلي',
                'verbose_name_plural': 'السجلات الفصلية',
                'ordering': ['-semester__year', '-semester__type'],
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
