# Generated by Django 6.0.7 on 2026-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_academicrecord_semesterrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الفصل الدراسي الحالي'),
        ),
    ]
