# Generated by Django 6.0.7 on 2026-07-24 21:18

from django.db import migrations


def seed_student_statuses(apps, schema_editor):
    StudentStatus = apps.get_model('student', 'StudentStatus')
    Student = apps.get_model('student', 'Student')
    
    allowed_statuses = ["جديد", "منتظم", "موقف قيده", "سحب ملف", "إخلاء طرف"]
    
    # 1. تهيئة الحالات الخمسة أولاً
    for name in allowed_statuses:
        StudentStatus.objects.get_or_create(name=name)
        
    # 2. جلب الحالات الخمسة للربط
    status_objects = {status.name: status for status in StudentStatus.objects.filter(name__in=allowed_statuses)}
    
    # 3. دمج ونقل الطلاب من المسميات القديمة إلى الجديدة
    old_pending = StudentStatus.objects.filter(name="مقبول جديد (غير مفعل)").first()
    if old_pending:
        Student.objects.filter(student_status=old_pending).update(student_status=status_objects["جديد"])
        old_pending.delete()
        
    old_active = StudentStatus.objects.filter(name="مستمر").first()
    if old_active:
        Student.objects.filter(student_status=old_active).update(student_status=status_objects["منتظم"])
        old_active.delete()
        
    old_suspended = StudentStatus.objects.filter(name="موقوف قيده").first()
    if old_suspended:
        if old_suspended.id != status_objects["موقف قيده"].id:
            Student.objects.filter(student_status=old_suspended).update(student_status=status_objects["موقف قيده"])
            old_suspended.delete()
            
    # 4. التأكد من نقل الطلاب ذوي الحالات غير المعتمدة
    default_status = status_objects["منتظم"]
    for status in list(StudentStatus.objects.all()):
        if status.name not in allowed_statuses:
            Student.objects.filter(student_status=status).update(student_status=default_status)
            status.delete()


def rollback_student_statuses(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_academicrecord_semesterrecord'),
    ]

    operations = [
        migrations.RunPython(seed_student_statuses, rollback_student_statuses),
    ]
