# Generated by Django 6.0.7 on 2026-07-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20260725_0018'),
        ('student', '0003_student_current_semester'),
    ]

    operations = [
    ]
