# Generated by Django 6.0.7 on 2026-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_merge_20260725_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_changed_major',
            field=models.BooleanField(default=False, verbose_name='تم تغيير المسار سابقاً'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_change_count',
            field=models.IntegerField(default=0, verbose_name='عدد مرات تغيير المسار'),
        ),
    ]
