# Generated by Django 6.0.7 on 2026-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_has_changed_major_student_major_change_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الجواز'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
    ]
