# Generated by Django 6.0.7 on 2026-08-06 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_passport_number_alter_student_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedstudent',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_type',
        ),
        migrations.RemoveField(
            model_name='studentedithistory',
            name='student_type',
        ),
    ]
