# Generated by Django 6.0.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_deletedstudent_student_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='مفتاح QR الفريد'),
        ),
    ]
