# Generated by Django 5.2.7 on 2026-08-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationality',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='placeofbirth',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
    ]
