# Generated by Django 5.2.7 on 2026-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_nationality_is_active_placeofbirth_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='notifications', max_length=50, verbose_name='الأيقونة'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط التوجيه'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('renewal', 'تجديد القيد'), ('registration', 'تنزيل المواد'), ('midterm_grade', 'رصد درجات النصفي'), ('final_grade', 'رصد درجات النهائي'), ('department_change', 'تغيير المسار'), ('hold', 'إيقاف القيد'), ('clearance', 'إخلاء الطرف'), ('graduation', 'التخرج'), ('general', 'إشعار عام')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(default='إشعار جديد', max_length=255, verbose_name='العنوان'),
        ),
    ]
