# Generated by Django 5.2.7 on 2026-08-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_notification_icon_notification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('all', 'كافة المستخدمين'), ('student', 'الطلاب'), ('registrar', 'المسجل العام والإدارة'), ('admin', 'مدير النظام')], default='all', max_length=50, verbose_name='الفئة المستهدفة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_student', 'إضافة طالب جديد'), ('renewal', 'تجديد القيد'), ('registration', 'تنزيل المواد'), ('grade_approval', 'اعتماد درجات ونتائج'), ('midterm_grade', 'رصد درجات النصفي'), ('final_grade', 'رصد درجات النهائي'), ('department_change', 'تغيير المسار'), ('hold', 'إيقاف القيد'), ('clearance', 'إخلاء الطرف'), ('graduation', 'التخرج'), ('failed_three_times', 'إنذار رسوب 3 مرات'), ('general', 'إشعار عام')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='student.student', verbose_name='الطالب'),
        ),
    ]
