# Generated by Django 5.2.7 on 2026-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_notification_target_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], max_length=20, unique=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name',
            field=models.CharField(choices=[('أعزب/ـة', 'أعزب/ـة'), ('متزوج/ـة', 'متزوج/ـة')], max_length=50, unique=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_student', 'إضافة طالب جديد'), ('renewal', 'تجديد القيد'), ('registration', 'تنزيل المواد'), ('course_assignment', 'تعيين وتكليف مادة لأستاذ'), ('grade_recording', 'رصد واعتماد الدرجات'), ('grade_approval', 'اعتماد درجات ونتائج'), ('midterm_grade', 'رصد درجات النصفي'), ('final_grade', 'رصد درجات النهائي'), ('department_change', 'تغيير المسار'), ('hold', 'إيقاف القيد'), ('clearance', 'إخلاء الطرف'), ('graduation', 'التخرج'), ('failed_three_times', 'إنذار رسوب 3 مرات'), ('grade_appeal', 'طعون ومراجعة الدرجات'), ('professor_grade_reply', 'رد الأستاذ على كشف الدرجات'), ('grade_submission', 'إرسال واستيراد كشف درجات'), ('general', 'إشعار عام')], default='general', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('all', 'كافة المستخدمين'), ('student', 'الطلاب'), ('registrar', 'المسجل العام والإدارة'), ('graduates', 'قسم الخريجين'), ('graduate_officer', 'موظف قسم الخريجين'), ('exam_director', 'مدير الدراسة والامتحانات'), ('exams', 'قسم الدراسة والامتحانات'), ('admin', 'مدير النظام')], default='all', max_length=50, verbose_name='الفئة المستهدفة'),
        ),
    ]
