# Generated by Django 5.2.7 on 2026-08-31 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_gender_name_alter_maritalstatus_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollment_semester',
            field=models.CharField(blank=True, default='ربيع', max_length=50, verbose_name='فصل الالتحاق'),
        ),
        migrations.DeleteModel(
            name='DeletedStudent',
        ),
    ]
