# Generated by Django 5.2.7 on 2026-09-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_enrollment_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clearance_ready_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال متطلبات التخرج'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_ready_for_clearance',
            field=models.BooleanField(db_index=True, default=False, verbose_name='جاهز لإخلاء الطرف تلقائياً'),
        ),
    ]
