# Generated by Django 5.2.7 on 2026-09-03 18:36

from django.db import migrations, models


def convert_gender_ids_to_choices(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE student_student 
            SET gender = CASE 
                WHEN gender = '1' THEN 'F' 
                WHEN gender = '2' THEN 'M' 
                WHEN gender IN ('ذكر', 'M') THEN 'M'
                WHEN gender IN ('أنثى', 'F') THEN 'F'
                ELSE 'M' 
            END;
        """)


def reverse_gender_choices_to_ids(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE student_student 
            SET gender = CASE 
                WHEN gender = 'F' THEN '1' 
                WHEN gender = 'M' THEN '2' 
                ELSE '2' 
            END;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_student_clearance_ready_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1, verbose_name='الجنس'),
        ),
        migrations.RunPython(convert_gender_ids_to_choices, reverse_gender_choices_to_ids),
    ]
