"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path

# بناء المسار الأساسي للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jue3r^0blgy#v03=g+wth#%a%bp2cx$5tnm95jw=5lg@vt*$p-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'apps.users',
    'apps.student',
    'apps.renewal',
    'apps.grades',
    'apps.faculty',

]

# تسجيل الدخول وإعادة تعيين كلمة المرور
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'users:dashboard_redirect'
LOGOUT_REDIRECT_URL = 'users:login'

# ============================================
# إعدادات الجلسات وحماية تسجيل الدخول (Sessions Security)
# ============================================
# انتهاء الجلسة عند إغلاق المتصفح لمنع بقاء الحساب مفتوحاً للأجهزة المشتركة
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# مدة صلاحية الجلسة (3600 ثانية = ساعة واحدة من عدم النشاط)
SESSION_COOKIE_AGE = 3600

# تجديد انتهاء الجلسة مع كل تفاعل نشط من المستخدم
SESSION_SAVE_EVERY_REQUEST = True

# حماية ملفات تعريف الارتباط ضد XSS
SESSION_COOKIE_HTTPONLY = True

# مدة صلاحية رابط إعادة تعيين كلمة المرور (300 ثانية = 5 دقائق دقيقة بدقة)
PASSWORD_RESET_TIMEOUT = 300


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.users.middleware.StudentAccessControlMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 🔥 أضف هذا السطر
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.student.context_processors.notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# إعدادات قاعدة البيانات لـ PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'datehem',
        'USER': 'postgres',
        'PASSWORD': 'haj714',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Africa/Tripoli'
USE_I18N = True
USE_L10N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# ============================================
# إعدادات رفع الملفات (صور الطلاب...)
# ============================================

# عنوان URL الذي سيتم من خلاله الوصول إلى الملفات المرفوعة
MEDIA_URL = '/media/'

# المسار الفعلي على القرص الصلب حيث سيتم تخزين الملفات المرفوعة
MEDIA_ROOT = BASE_DIR / 'media'
# ============================================
# إعدادات البريد الإلكتروني (Email Configurations)
# ============================================

# ============================================
# إعداد وضع المحاكاة والنظام الزمني المركزي (Simulation Mode)
# ============================================
ENABLE_SIMULATION_MODE = True

