# Generated by Django 6.0.7 on 2026-07-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renewal', '0003_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='الرقم الوظيفي')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.department', verbose_name='القسم')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renewal.specialization', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.course', verbose_name='المادة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.department', verbose_name='القسم')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.level', verbose_name='المستوى')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.group', verbose_name='المجموعة')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.professor', verbose_name='الأستاذ')),
            ],
            options={
                'verbose_name': 'إسناد مادة لأستاذ',
                'verbose_name_plural': 'إسنادات المواد للأساتذة',
                'ordering': ['semester', 'course__code'],
                'unique_together': {('professor', 'course', 'student_group', 'semester')},
            },
        ),
    ]
