# Generated by Django 6.0.7 on 2026-07-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('renewal', '0004_department_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewal.specialization', verbose_name='التخصص'),
        ),
    ]
