# Generated by Django 6.0.7 on 2026-07-29 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_professor_specialization'),
        ('renewal', '0007_enrollmentrenewal_special_type_and_more'),
        ('student', '0004_merge_20260725_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الحضور')),
                ('day_number', models.IntegerField(default=1, verbose_name='رقم اليوم/المحاضرة')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('excused', 'بعذر')], default='present', max_length=20, verbose_name='حالة الحضور')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='renewal.course', verbose_name='المادة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewal.department', verbose_name='القسم')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewal.group', verbose_name='المجموعة')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renewal.semester', verbose_name='الفصل الدراسي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'سجل حضور وغياب',
                'verbose_name_plural': 'سجلات الحضور والغياب',
                'ordering': ['-date', 'student__name'],
            },
        ),
    ]
