# Generated by Django 5.2.7 on 2026-07-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_attendancerecord'),
        ('renewal', '0008_courseequivalence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='الرقم الوظيفي')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(max_length=150, verbose_name='المسمى الوظيفي / الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renewal.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'موظف قسم',
                'verbose_name_plural': 'موظفو الأقسام',
                'ordering': ['full_name'],
            },
        ),
    ]
